// Final stage of the codegen pipeline. Reads the spec (`dist/spec.json`)
// and emits `dist/api.gen.ts`, which groups the flat per-operation
// functions hey-api wrote into `dist/generated/` under one object per
// slice:
//
//   createApiClient({ client })
//      .repository.list(...)
//      .repository.get({ params: { repositoryId } })
//      .....
//
// The backend's emitter stamps every operation with `operationId`,
// `x-tailor-slice`, and `x-tailor-method`. This stage just wires
// `api.<slice>.<method>` to the SDK function whose name equals the
// operationId.
import fs from 'node:fs/promises';
import path from 'node:path';
import {
  ALIASES_PATH,
  NAMESPACE_PATH,
  SPEC_PATH,
  TYPES_PATH,
  isScriptEntrypoint,
} from './paths.ts';

// The subset of OpenAPI operation fields this stage reads.
interface TailorOperation {
  // Name of the SDK function in `./generated/sdk.gen.ts`
  // (hey-api uses operationId as the function name in flat mode).
  'operationId'?: string;
  // Codegen namespace key, e.g. `repository`, `tag`, `library`.
  'x-tailor-slice'?: string;
  // Property name on the namespace object, e.g. `list`, `publish`.
  'x-tailor-method'?: string;
}

interface OpenApiDoc {
  paths?: Record<string, Record<string, TailorOperation>>;
}

interface Namespace {
  // Codegen slice key (`repository`, `tag`, ...). Becomes the property
  // name on the root `createApiClient(...)` object.
  key: string;
  // Operations belonging to this slice, sorted by `methodName`.
  ops: ResolvedOp[];
}

interface ResolvedOp {
  // Symbol imported from `./generated/sdk.gen.ts`. Equals the
  // operationId hey-api saw in the spec.
  operationId: string;
  // Property name on the public namespace object;
  // `api.<slice>.<methodName>`. Equals the spec's `x-tailor-method`.
  methodName: string;
}

interface BuildResult {
  // The full source for `dist/api.gen.ts`.
  code: string;
  // The full source for `dist/aliases.gen.ts` (hey-api's `*Data`/
  // `*Responses`/`*Errors` re-exported under `*Req`/`*Res`/`*Err`).
  aliasesCode: string;
  // Number of top-level namespaces on the generated client.
  namespaceCount: number;
  // Total operations wired across all namespaces.
  operationCount: number;
}

const HTTP_METHODS = new Set([
  'get', 'post', 'put', 'patch', 'delete', 'head', 'options', 'trace',
]);

// Type plumbing emitted into the generated module.
const RUNTIME_TYPES = [
  'type Operation = (...args: any[]) => any;',
  'type Body<O extends Operation> = NonNullable<',
  '  Awaited<ReturnType<O>> extends { data: infer D } ? D : never',
  '>;',
  'type Unwrap<B> = B extends { data: infer D } ? D : B;',
  'type Data<O extends Operation> = Unwrap<Body<O>>;',
  'type RawOptions<O extends Operation> = Omit<',
  '  Parameters<O>[0],',
  '  "client" | "throwOnError" | "path"',
  '>;',
  'type PathOf<O extends Operation> = Parameters<O>[0] extends { path: infer P }',
  '  ? P',
  '  : undefined;',
  'type Bound<O extends Operation> =',
  '  PathOf<O> extends undefined',
  '    ? (options?: RawOptions<O>) => Promise<Data<O>>',
  '    : (options: RawOptions<O> & { params: PathOf<O> }) => Promise<Data<O>>;',
  '',
  'export interface ApiClientOptions {',
  '  client: Client;',
  '}',
].join('\n');

const renderImports = (operationIds: string[]): string => [
  'import type { Client } from \'@hey-api/client-axios\';',
  '',
  'import {',
  ...operationIds.map((name) => `  ${name},`),
  '} from \'./generated/sdk.gen.js\';',
].join('\n');

const renderNamespace = ({ key, ops }: Namespace): string => {
  const body = ops
    .map(({ methodName, operationId }) => (
      `      ${methodName}: bind(${operationId}),`
    ))
    .join('\n');
  return `    ${key}: {\n${body}\n    },`;
};

// hey-api emits per-operation types named `<OperationId>Data` (request
// input shape - path + body + query + url), `<OperationId>Responses`
// (status -> response body map), and `<OperationId>Errors` (status ->
// error body map).
const ALIAS_SUFFIXES: ReadonlyArray<{ from: string; to: string }> = [
  { from: 'Data', to: 'Req' },
  { from: 'Responses', to: 'Res' },
  { from: 'Errors', to: 'Err' },
];

// Returns `Capitalize<operationId>` so `activityList` → `ActivityList`,
// matching how hey-api names its per-operation types.
const pascalOpId = (op: string): string =>
  op.length === 0 ? op : op[0]!.toUpperCase() + op.slice(1);

const renderAliases = (
  operationIds: string[],
  exportedNames: Set<string>,
): string => {
  const lines: string[] = [
    '// AUTOGENERATED by scripts/build-namespace.ts. Do not edit.',
    '// Re-exports hey-api\'s `*Data`/`*Responses`/`*Errors` operation',
    '// types under shorter, less ambiguous names:',
    '//   `*Data`      → `*Req`        (request input: path + body + query)',
    '//   `*Responses` → `*Res`        (status → response body map)',
    '//   `*Response`  → `*Result`     (singular response body)',
    '//   `*Errors`    → `*Err`        (status → error body map)',
    '//   `*Error`     → `*ErrResult`  (singular error body)',
    '',
  ];
  for (const operationId of operationIds) {
    const base = pascalOpId(operationId);
    const renames = ALIAS_SUFFIXES
      .filter(({ from }) => exportedNames.has(`${base}${from}`))
      .map(({ from, to }) => `  ${base}${from} as ${base}${to},`)
      .join('\n');
    if (!renames) continue;
    lines.push(`export type {\n${renames}\n} from './generated/types.gen.js';`);
  }
  return lines.join('\n') + '\n';
};

// Walks hey-api's `types.gen.ts` source and returns every top-level
// `export type Foo` symbol
const collectExportedTypeNames = async (): Promise<Set<string>> => {
  const src = await fs.readFile(TYPES_PATH, 'utf-8');
  const names = new Set<string>();
  for (const match of src.matchAll(/^export type (\w+)/gm)) {
    names.add(match[1]!);
  }
  return names;
};

const renderModule = (
  namespaces: Namespace[],
  operationIds: string[],
): string => [
  '// AUTOGENERATED by scripts/build-namespace.ts. Do not edit.',
  '// Run `pnpm generate` to regenerate.',
  '',
  renderImports(operationIds),
  '',
  RUNTIME_TYPES,
  '',
  'export function createApiClient({ client }: ApiClientOptions) {',
  '  const bind = <O extends Operation>(fn: O): Bound<O> =>',
  '    (async (options: Record<string, unknown> | undefined) => {',
  '      // Translate caller-facing `params` to hey-api\'s `path`.',
  '      const { params, ...rest } = options ?? {};',
  '      const res = await fn({',
  '        ...rest,',
  '        ...(params !== undefined ? { path: params } : {}),',
  '        client,',
  '        throwOnError: true,',
  '      });',
  '      // Peel the `{ data: ... }` envelope (see `Bound`\'s `Unwrap`).',
  '      const body = res.data;',
  '      return body && typeof body === \'object\' && \'data\' in body',
  '        ? body.data',
  '        : body;',
  '    }) as Bound<O>;',
  '',
  '  return {',
  ...namespaces.map(renderNamespace),
  '  };',
  '}',
  '',
].join('\n');

class NamespaceBuilder {
  private readonly byNamespace = new Map<string, ResolvedOp[]>();
  private readonly operationIds = new Set<string>();

  constructor(private readonly doc: OpenApiDoc) {}

  build(exportedNames: Set<string>): BuildResult {
    this.collect();
    const namespaces = this.sortedNamespaces();
    const operationIds = [...this.operationIds].sort();
    return {
      code: renderModule(namespaces, operationIds),
      aliasesCode: renderAliases(operationIds, exportedNames),
      namespaceCount: namespaces.length,
      operationCount: operationIds.length,
    };
  }

  private collect(): void {
    for (const [urlPath, pathItem] of Object.entries(this.doc.paths ?? {})) {
      for (const [method, op] of Object.entries(pathItem)) {
        if (!HTTP_METHODS.has(method)) continue;
        this.appendOp(method, urlPath, op);
      }
    }
  }

  private appendOp(
    method: string,
    urlPath: string,
    op: TailorOperation,
  ): void {
    const slice = op['x-tailor-slice'];
    const methodName = op['x-tailor-method'];
    const { operationId } = op;
    if (!slice || !methodName || !operationId) {
      throw new Error(
        `Operation ${method.toUpperCase()} ${urlPath} is missing `
        + 'operationId / x-tailor-slice / x-tailor-method; '
        + 'the backend emitter should populate them.',
      );
    }
    const bucket = this.byNamespace.get(slice) ?? [];
    bucket.push({ operationId, methodName });
    this.byNamespace.set(slice, bucket);
    this.operationIds.add(operationId);
  }

  private sortedNamespaces(): Namespace[] {
    return [...this.byNamespace]
      .map(([key, ops]) => ({
        key,
        ops: [...ops].sort((a, b) => a.methodName.localeCompare(b.methodName)),
      }))
      .sort((a, b) => a.key.localeCompare(b.key));
  }
}

export const buildNamespace = async (): Promise<BuildResult> => {
  const raw = await fs.readFile(SPEC_PATH, 'utf-8');
  const doc = JSON.parse(raw) as OpenApiDoc;
  const exportedNames = await collectExportedTypeNames();
  const result = new NamespaceBuilder(doc).build(exportedNames);
  await fs.mkdir(path.dirname(NAMESPACE_PATH), { recursive: true });
  await fs.writeFile(NAMESPACE_PATH, result.code);
  await fs.writeFile(ALIASES_PATH, result.aliasesCode);
  console.log(
    `Wrote ${NAMESPACE_PATH} (${result.namespaceCount} namespaces, `
    + `${result.operationCount} operations).`,
  );
  console.log(
    `Wrote ${ALIASES_PATH} (${result.operationCount} operations re-aliased).`,
  );
  return result;
};

if (isScriptEntrypoint(import.meta.url)) {
  buildNamespace().catch((err: unknown) => {
    console.error(err);
    process.exit(1);
  });
}
