name: Setup node, pnpm, install dependencies
runs:
  using: composite
  steps:
  - uses: pnpm/action-setup@v2
    with:
      version: 9.4.0
  - name: Setup node to enable caching
    uses: actions/setup-node@v3
    with:
      node-version: 22.1
      cache: 'pnpm'
      cache-dependency-path: './pnpm-lock.yaml'
  - name: Install dependencies
    shell: bash
    run: pnpm i
