# TODO: Make all env variables configurable
services:
  postgres:
    container_name: "tailor-postgres"
    image: "postgres:15.1"
    environment:
      POSTGRES_DB: "tailor_dev"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: "no"
  redis:
    container_name: "tailor-redis"
    image: redis:7.4.0
    ports:
      - "6379:6379"
  localstack:
    container_name: tailor-localstack
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      - SERVICES=s3:4566
      - DEFAULT_REGION=us-east-1
