# TODO: Make all env variables configurable
services:
  postgres:
    container_name: "postgres"
    image: "postgres:15.1"
    environment:
      POSTGRES_DB: "tailor_dev"
      POSTGRES_USER: "dev"
      POSTGRES_PASSWORD: "dev"
    expose:
      - "5432"
    restart: "no"
