services:
  author-dev-postgres:
    container_name: 'author-dev-postgres'
    image: 'postgres:15.1'
    environment:
      POSTGRES_DB: 'tailor_dev'
      POSTGRES_USER: 'dev'
      POSTGRES_PASSWORD: 'dev'
    expose:
      - '5432'
    ports:
      - '5432:5432'
    restart: 'no'
  author-dev-redis:
    container_name: 'author-dev-redis'
    image: redis:7.4.0
    expose:
      - '6379'
    ports:
      - '6379:6379'
  author-dev-minio:
    container_name: author-dev-minio
    image: minio/minio
    command: server /data
    expose:
      - '9000'
    ports:
      - '4566:9000'
    environment:
      - MINIO_ROOT_USER=test
      - MINIO_ROOT_PASSWORD=test1234
  author-dev-createbucket:
    image: minio/mc
    depends_on:
      - author-dev-minio
    entrypoint: >
      /bin/sh -c "
      sleep 3;
      mc alias set minio http://author-dev-minio:9000 test test1234;
      mc mb minio/test --ignore-existing;
      exit 0;
      "
