packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/core-extensions/meta-inputs/*'
  - 'packages/core-extensions/content-containers/*'
  - 'packages/core-extensions/content-elements/*'
  - 'tests'
  - 'extensions/content-elements'
  - 'extensions/meta-inputs'
  - 'extensions/content-containers'
  - 'infrastructure'
  - 'config'
