name: Setup Tailor for E2E testing
runs:
  using: composite
  steps:
  - uses: pnpm/action-setup@v2
    with:
      version: 8.6.12
  - uses: actions/setup-node@v3
    with:
      node-version: 18.16
      cache: 'pnpm'
      cache-dependency-path: './pnpm-lock.yaml'
  - name: Install dependencies
    shell: bash
    run: pnpm i
  - uses: actions/cache@v3
    name: Check Playwright cache
    id: playwright-cache
    with:
      path: ~/.cache/ms-playwright
      key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
  - name: Install Playwright
    shell: bash
    run: pnpm dlx playwright@${{ env.PLAYWRIGHT_VERSION }} install --with-deps
    if: steps.playwright-cache.outputs.cache-hit != 'true'
  - name: Run service deps via Docker
    uses: isbang/compose-action@v1.3.2
    with:
      compose-file: docker-compose.dev.yaml
  - name: Configure env and build
    shell: bash
    run: pnpm setup:dev
  - name: Run
    shell: bash
    run: pnpm dev & sleep 20
  - name: Check if Tailor is available
    uses: fjogeleit/http-request-action@v1
    with:
      url: 'http://localhost:8080'
      method: 'GET'
      contentType: text/html
      retry: 5
      retryWait: 4000
      timeout: 20000
