export const ContentElementType = {
  HtmlDefault: 'CE_HTML_DEFAULT',
  Image: 'CE_IMAGE',
  MultipleChoice: 'CE_MULTIPLE_CHOICE',
  SingleChoice: 'CE_SINGLE_CHOICE',
  MatchingQuestion: 'CE_MATCHING_QUESTION',
  TextResponse: 'CE_TEXT_RESPONSE',
  TrueFalse: 'CE_TRUE_FALSE',
  NumericalResponse: 'CE_NUMERICAL_RESPONSE',
  FillBlank: 'CE_FILL_BLANK',
  PageBreak: 'CE_PAGE_BREAK',
  DragDrop: 'CE_DRAG_DROP',
  Pdf: 'CE_PDF',
  Embed: 'CE_EMBED',
  Audio: 'CE_AUDIO',
  Video: 'CE_VIDEO',
};
