export const ContentElementType = {
  TiptapHtml: 'TIPTAP_HTML',
  Image: 'IMAGE',
  MultipleChoice: 'MULTIPLE_CHOICE',
  SingleChoice: 'SINGLE_CHOICE',
  MatchingQuestion: 'MATCHING_QUESTION',
  TextResponse: 'TEXT_RESPONSE',
  TrueFalse: 'TRUE_FALSE',
  NumericalResponse: 'NUMERICAL_RESPONSE',
  FillBlank: 'FILL_BLANK',
  Break: 'BREAK',
  DragDrop: 'DRAG_DROP',
  Pdf: 'PDF',
  Embed: 'EMBED',
  Audio: 'AUDIO',
  Video: 'VIDEO',
  Accordion: 'ACCORDION',
  Carousel: 'CAROUSEL',
  Modal: 'MODAL',
  Table: 'TABLE',
  BrightcoveVideo: 'BRIGHTCOVE_VIDEO',
  JoditHtml: 'JODIT_HTML',
  Html: 'HTML',
  File: 'FILE',
  HtmlRaw: 'HTML_RAW',
  MuxVideo: 'MUX_VIDEO',
};
